# This is a basic workflow to help you get started with Actions
name: Connect to an AWS role from a GitHub repository

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    tags:
      - dev
env:
  AWS_REGION : "us-east-1"
  ROLE : "arn:aws:iam::779846793683:role/development-github-connec-githubidpghidproleAF42990-lD5MLGDPNfK3"

# Permission can be added at job level or workflow level
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  Ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Set up Python 3.13.1
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.1"
      - name: Install Ruff
        run: |
          python -m pip install ruff
      - name: ruff
        run: |
          ruff format --check && ruff check
  Pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Set up Python 3.13.1
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.1"
      - name: Install Python dependencies
        run: |
          python -m pip install uv
          uv pip install -r requirements/dev.txt --system --require-hashes
      - name: pytest
        run: |
          pytest
  Mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Set up Python 3.13.1
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.1"
      - name: Install Python dependencies
        run: |
          python -m pip install uv
          uv pip install -r requirements/dev.txt --system --require-hashes
      - name: mypy
        run: |
          mypy .
  BuildAndDeploy:
    runs-on: ubuntu-latest
    needs: [Ruff, Pytest, Mypy]
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Set up Python 3.13.1
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.1"
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install Deploy dependencies
        run: |
          python -m pip install uv
          uv pip install -r requirements/dev.txt --system --require-hashes
          npm install -g aws-cdk
      - name: Build
        run: |
          ./scripts/build.sh
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy
        run: |
          pwd
          cdk deploy development/** --app="python3 ${PWD}/app.py" --require-approval=never
